[build]
  base = "/"
  publish = "dist/"
  directory = "functions/"
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://family-search-image.netlify.app"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
